//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballApp.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_To_Stadion
    {
        public int Id { get; set; }
        public int StadionId { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Stadion Stadion { get; set; }
    }
}
